apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-rollout-dev
spec:
  params:
    - description: Quay username.
      name: quayuser
      type: string
      default: pittar
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/pittar/spring-petclinic.git'
        - name: revision
          value: devsecops
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: mvn
      params:
        - name: MAVEN_IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/openshift/java:latest
        - name: GOALS
          value:
            - clean
            - package
            - deploy
            - '-DskipTests'
        - name: MAVEN_MIRROR_URL
          value: ''
        - name: MAVEN_REPO_CONFIG_SECRET
          value: maven-secret
        - name: M2_DIRECTORY
          value: /home/jboss/.m2/
        - name: SERVER_USER
          value: ''
        - name: SERVER_PASSWORD
          value: ''
        - name: PROXY_USER
          value: ''
        - name: PROXY_PASSWORD
          value: ''
        - name: PROXY_PORT
          value: ''
        - name: PROXY_HOST
          value: ''
        - name: PROXY_NON_PROXY_HOSTS
          value: ''
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: .
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: mvn
      workspaces:
        - name: source
          workspace: workspace
        - name: maven-settings
          workspace: maven-settings
    - name: build-image
      params:
        - name: IMAGE
          value: 'quay.io/$(params.quayuser)/petclinic:latest'
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Containerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: SKIP_PUSH
          value: 'false'
      runAfter:
        - mvn
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: workspace
    - name: acs-scan-image
      taskRef:
        name: acs-image-scan
        kind: ClusterTask
      runAfter:
        - build-image
      params:
        - name: output_format
          value: table
        - name: image
          value: quay.io/$(params.quayuser)/petclinic@$(tasks.build-image.results.IMAGE_DIGEST)
      workspaces:
        - name: acs-central
          workspace: acs-central
    - name: acs-check-image
      taskRef:
        name: acs-image-check
        kind: ClusterTask
      runAfter:
        - acs-scan-image
      params:
        - name: image
          value: quay.io/$(params.quayuser)/petclinic@$(tasks.build-image.results.IMAGE_DIGEST)
      workspaces:
        - name: acs-central
          workspace: acs-central
    - name: skopeo-copy-dev
      runAfter:
        - acs-check-image
      taskRef:
        kind: ClusterTask
        name: skopeo-copy
      params:
        - name: srcImageURL
          value: 'docker://quay.io/$(params.quayuser)/petclinic@$(tasks.build-image.results.IMAGE_DIGEST)'
        - name: destImageURL
          value: 'docker://quay.io/$(params.quayuser)/petclinic:dev'
        - name: srcTLSverify
          value: 'true'
        - name: destTLSverify
          value: 'true'
      workspaces:
        - name: images-url
          workspace: workspace
    - name: rollout-dev
      params:
        - name: SCRIPT
          value: oc rollout restart deployment petclinic -n petclinic-dev
        - name: VERSION
          value: latest
      runAfter:
        - skopeo-copy-dev
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: skopeo-copy-test
      runAfter:
        - rollout-dev
      taskRef:
        kind: ClusterTask
        name: skopeo-copy
      params:
        - name: srcImageURL
          value: 'docker://quay.io/$(params.quayuser)/petclinic@$(tasks.build-image.results.IMAGE_DIGEST)'
        - name: destImageURL
          value: 'docker://quay.io/$(params.quayuser)/petclinic:test'
        - name: srcTLSverify
          value: 'true'
        - name: destTLSverify
          value: 'true'
      workspaces:
        - name: images-url
          workspace: workspace
    - name: openshift-client
      params:
        - name: SCRIPT
          value: oc rollout restart deployment petclinic -n petclinic-test
        - name: VERSION
          value: latest
      runAfter:
        - skopeo-copy-test
      taskRef:
        kind: ClusterTask
        name: openshift-client
  workspaces:
    - name: workspace
    - name: maven-settings
    - name: acs-central
