apiVersion: v1
kind: Secret
metadata:
  name: maven-secret
stringData:
  MAVEN_SERVER_USERNAME: admin
  MAVEN_SERVER_PASSWORD: admin123
  MAVEN_SERVER_HOST: http://nexus.nexus.svc.cluster.local:8081
  SONAR_SERVER_HOST: http://sonarqube.cicd-tools.svc.cluster.local:9000