apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: quay-credentials
spec:
  params:
    - description: Quay username.
      name: username
      type: string
    - description: Quay password.
      name: password
      type: string
  tasks:
    - name: create-quay-creds-secreet
      params:
        - name: SCRIPT
          value: |
            echo "Create quay creds secret."
            oc create secret generic quay-creds \
              --from-literal=username=$(params.username) \
              --from-literal=password=$(params.password)

            echo "Annotate secret for tekton."

            oc annotate secret quay-creds \
              tekton.dev/docker-0=https://quay.io
        - name: VERSION
          value: latest
      taskRef:
        kind: ClusterTask
        name: openshift-client
