kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: petclinicdb
    app.kubernetes.io/component: petclinicdb
    app.kubernetes.io/instance: petclinicdb
    app.kubernetes.io/name: petclinicdb
    app.kubernetes.io/part-of: petclinic
    app.openshift.io/runtime: mysql-database
    app.openshift.io/runtime-namespace: openshift
    app.openshift.io/runtime-version: '8.0'
  name: petclinicdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinicdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: petclinicdb
        deployment: petclinicdb
    spec:
      volumes:
      - name: petclinicdb-data
        persistentVolumeClaim:
          claimName: petclinicdb
      containers:
      - name: mysql
        image: image-registry.openshift-image-registry.svc:5000/openshift/mysql:8.0
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: petclinicdb
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: petclinicdb
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-root-password
              name: petclinicdb
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: petclinicdb
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3306
          timeoutSeconds: 1
        ports:
        - containerPort: 3306
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE
              -e 'SELECT 1'
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql/data
          name: petclinicdb-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

